### ISSUE TITLE
For some reason, this requires struct field names to be capitalized

### ISSUE THREAD

**Issue by Zireael07** [yuin/gluamapper#5]
```
type Person struct {
    name      string
}

```
will not work, without any sort of a user-visible error.

**Comment by Feresey** [comment]
This is how go reflection works, close the issue.

**Comment by Zireael07** [comment]
Yeah, but this should be mentioned in the README somewhere - not every user of the library is proficient in Go.

**Comment by Feresey** [comment]
This is mentioned in golang Readme)
